on:
  push:
    branches: ["master"]

name: Release

env:
  APPLICATION: uptime
  AWS_REGION: eu-west-1

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@cb66b82ec859c0a491fac75d3cabf2786144330b
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@cef2380b0d4c6813048ef6e1f7fd9ec1639bd3b5

      - name: Generate tag
        id: tag
        run: echo "::set-output name=value::$(date '+%Y%m%d-%H%M')"

      - uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$APPLICATION:${{ steps.tag.outputs.value }} .
          docker push $ECR_REGISTRY/$APPLICATION:${{ steps.tag.outputs.value }}
          echo "image=$ECR_REGISTRY/$APPLICATION:${{ steps.tag.outputs.value }}" >> $GITHUB_OUTPUT
